# Generated by Django 6.0.5 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('6-Bed Shared Dorm', '6-Bed Shared Dorm'), ('4-Bed Shared Dorm', '4-Bed Shared Dorm'), ('2-Bed Shared Dorm', '2-Bed Shared Dorm'), ('Private Single Room', 'Private Single Room'), ('Need Guidance', 'Need Guidance')], max_length=100)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
